"""create hotspots and industrial assets

Revision ID: f4f1a00d9c56
Revises: 
Create Date: 2026-09-07 15:33:29.863364

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f1a00d9c56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotspots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('frp', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('nearest_asset_id', sa.UUID(), nullable=True),
    sa.Column('distance_to_asset_m', sa.Float(), nullable=True),
    sa.Column('landcover_class', sa.String(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('predicted_class', sa.String(), nullable=True),
    sa.Column('prediction_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industrial_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('industrial_assets')
    op.drop_table('hotspots')
    # ### end Alembic commands ###
